version: '3.9'
services:
  
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8082:80"
    networks:
      - internal
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./data:/var/www/html
      
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./data:/var/www/html
    ports:
      - "9000:9000"

networks:
  internal:
    driver: bridge