name: CI/CD LaGranjita DEV
on:
  push:
    branches: [main]

jobs: 
  job_one:  
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Auto Pull LaGranjita DEV
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USR_NAME }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/lagranjita/public_html/
            git status
            git pull origin main
            git log -1
