name: Integracion Continua Web Page LaGranjita
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Continue_Integration:
    runs-on: ubuntu-latest
    steps:
    - name: SSH to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USR_NAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd lagranjita/
          git pull origin main --ff-only
    - uses: actions/checkout@v2
    - name: Telegram Notification
      uses: appleboy/telegram-action@master
      with:
        to: '-1002082761148'
        token: '6844458606:AAGYYpQDieh-sv-gyjGXBVd1mhQoiTqQ-2I'
        message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      # env:
      #   SLACK_CHANNEL: ci-cd
      #   SLACK_COLOR: ${{ job.status }}
      #   SLACK_MESSAGE: 'Tarea Finalizada 🚀 done by 😎 ${{ github.actor }} message 🗨️ ${{ github.event.head_commit.message }}'
      #   SLACK_TITLE: '🚦Estado de la tarea: ${{ job.status }}'
      #   SLACK_USERNAME: CICD
      #   SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}