name: CI/CD LaGranjita
on:
  push:
    branches: [main]

jobs: 
  job_one:  
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Auto Pull LaGranjita
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USR_NAME }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/lagranjita/public_html/
            git status
            git pull origin main
            git log -1
