name: CI/CD LaGranjita DEV
on:
  push:
    branches: [QAGranjita]

jobs: 
  job_one:  
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Auto Pull LaGranjita DEV
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USR_NAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWD }}
          script: |
            su
            ${{ secrets.PASSWD }}
            cd /var/www/html
            git status
            git pull origin QAGranjita
            git log -1
