name: autopull
on:
  push:
    branches: [main]

jobs: 
  job_one:  
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Auto Pull Origin main
        uses: appleboy/ssh-action@master
        with:
          host: beta.lagranjitaonline.com
          username: admin
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /var/www/html
            git status
            git pull origin main
            git log -1
